### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by urgas9** [slok/go-http-metrics#159]
@slok any chance we release a new version?

There have been many dependency bumps with security fixes that are not present in the latest release.

**Comment by NajeebTyson** [comment]
@slok can you take some action on this kindly?

**Comment by slok** [comment]
Hi!

I will copy/paste the same thing I have put in another issue that asks more or less the same :)

>Thanks, yes the repo has been a bit outdated but stable, I understand the concerns, however, I will try to do my best to keep up to date.
>I just updated all dependencies in a new release.

Best!
