### ISSUE TITLE
Repo still maintained?

### ISSUE THREAD

**Issue by jack-evans** [slok/go-http-metrics#191]
@slok is this repo still maintained? Seems like there has been no commit to master for 11 months and no release for 2 years. Really find this repo useful but we may have to abandon using it if the security fixes aren't patched

**Comment by slok** [comment]
Hi!

Thanks, yes the repo has been a bit outdated but stable, I understand the concerns, however, I will try to do my best to keep up to date.

I just updated all dependencies in a new release.

Best!
