### ISSUE TITLE
support the http.Hijacker interface in middleware.responseWriterInterceptor

### ISSUE THREAD

**Issue by draeron** [slok/go-http-metrics#28]
If a another middleware try to hijack the connection, the wrapper won't forward the call to hijack. In my case the middleware tries to upgrade the connection to a websocket.

This is how it's implemented in Negroni :
https://github.com/urfave/negroni/blob/master/response_writer.go#L82

**Comment by slok** [comment]
Hi there @draeron
Thanks for the report! Will try checking the interceptors this week! :smile:

**Comment by slok** [comment]
[New release tag](https://github.com/slok/go-http-metrics/releases/tag/v0.6.1) with the bugfix, Sorry for the bug!

**Comment by draeron** [comment]
thanks for the fix!
