### ISSUE TITLE
example with gin does not work properly

### ISSUE THREAD

**Issue by yechongbo** [slok/go-http-metrics#31]
with the response type as json, it produces two items in output.

**Comment by slok** [comment]
Hi @yechongbo thanks for opening the issue! I'll try to take a look this week

**Comment by fungiboletus** [comment]
Meanwhile, using the default example with http.Handler works fine.

**Comment by slok** [comment]
Hi @yechongbo and @fungiboletus!

I just published a new release that has the fix that was merged some days ago: https://github.com/slok/go-http-metrics/releases/tag/v0.7.0
