### ISSUE TITLE
Wrapper for handlerID parsing

### ISSUE THREAD

**Issue by alewkinr** [slok/go-http-metrics#44]
Hello there! 
It'd be awesome to have extra param for new `std.Handler` method, so we could pass formatting function to get clear handlerID in `Measure.

Now it's painful, 'coz I need to extract request url via dirty function or wrap in one more time.

**Comment by alewkinr** [comment]
Fixed situation, implementing `CustomResponseInterseptor` and  `CustomReporter`

**Comment by slok** [comment]
Hi @alewkinr! sorry for the delayed response.

Yes, you are right, the correct way to go in this situation would be implementing your own Reporter, taking as an example the ones the library has built-in.

Other applications are already using this method (e.g [kumahq/kuma](https://github.com/kumahq/kuma/blob/4eb1773b0aa67c7991219bafed3cf70904340859/pkg/util/prometheus/gorestful_middleware.go))

One of the reasons for creating the reporter was that, adding an easy way of extending to any kind of framework or custom usage (like yours) in an elegant way. Requires a little bit of work, however, the outcome is very good and clean.

Should we close the issue?

Thanks!

**Comment by alewkinr** [comment]
yep, thx
Close this issue, please
