### ISSUE TITLE
Possible to release new version?

### ISSUE THREAD

**Issue by mattwiller** [slok/go-http-metrics#90]
There's been lots of great activity in the repository, but no new release for over a year.  Would it be possible to release a new version?  There have been security vulnerabilities in the `echo`, `gin`, and `protobuf` dependencies; it appears that the latest `go.mod` refers to the fixed versions, and it would be so helpful to close those security holes for users of the library

**Comment by slok** [comment]
Hi @mattwiller 

Thanks for bringing this, I've been busy at work and maintaining https://github.com/slok/sloth.

I'll try updating some libraries and publishing a new release next week!

Best,

**Comment by slok** [comment]
Hi @mattwiller!

[v0.10.0](https://github.com/slok/go-http-metrics/releases/tag/v0.10.0) Is out! Closing the issue, if you have any problem, please open a new Issue :)

**Comment by mattwiller** [comment]
@slok Thank you — much appreciated!
