### ISSUE TITLE
go http client example

### ISSUE THREAD

**Issue by Tochemey** [slok/go-http-metrics#91]
Thanks for this great piece of work. I would like to know whether there is an example on how to use it with the http client.

**Comment by slok** [comment]
Hi @Tochemey, Sorry but I don't understand what do you mean exactly. This library is to measure server-side, not the client-side. All the available examples you have them [here](https://github.com/slok/go-http-metrics/tree/master/examples).

**Comment by slok** [comment]
Closing, if you need further help, please open a new issue :) thanks!
